# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all

matt = User.create(first_name: 'Matt', username: 'matt18', password: '18', age: 27, gender: 'Male', bio: 'I made this', college: 'Williams College', occupation: 'Software Engineer')

Topic.create(name: 'Aliens')
Topic.create(name: 'Alcohol')
Topic.create(name: 'Animal Rights')
Topic.create(name: 'Artificial Intelligence')
Topic.create(name: 'Astrology')
Topic.create(name: 'Charity')
Topic.create(name: 'Children')
Topic.create(name: 'Climate')
Topic.create(name: 'Coffee and Tea')
Topic.create(name: 'Culture')
Topic.create(name: 'Dogs')
Topic.create(name: 'Economy')
Topic.create(name: 'Education')
Topic.create(name: 'Electronics')
Topic.create(name: 'Entertainment')
Topic.create(name: 'Environment')
Topic.create(name: 'Equality')
Topic.create(name: 'Fashion')
Topic.create(name: 'Family')
Topic.create(name: 'Finance')
Topic.create(name: 'Fitness')
Topic.create(name: 'Food')
Topic.create(name: 'Friendship')
Topic.create(name: 'Gaming')
Topic.create(name: 'Health')
Topic.create(name: 'Human Rights')
Topic.create(name: 'Local News and Events')
Topic.create(name: 'Movies')
Topic.create(name: 'Music')
Topic.create(name: 'Mathematics')
Topic.create(name: 'Mental Health')
Topic.create(name: 'Money')
Topic.create(name: 'News')
Topic.create(name: 'Parenthood')
Topic.create(name: 'Pregnancy')
Topic.create(name: 'Politics')
Topic.create(name: 'Programming')
Topic.create(name: 'Relationships')
Topic.create(name: 'Sex')
Topic.create(name: 'Social Media')
Topic.create(name: 'Sports')
Topic.create(name: 'Technology')
Topic.create(name: 'Travel')
Topic.create(name: 'TV')
Topic.create(name: 'Volunteer Work')
Topic.create(name: 'Work')
